version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=javareachabilityplayground007 -Dsonar.organization=javareachabilityplayground007 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=token 
